Repository rojo-rbx/rojo, pull requests merged in 2023-10, with the labels that each got.

#793 Don't include package author in CLI help
  src/cli/mod.rs
Labels: scope: cli, skip changelog

#794 Add check to ensure plugin version matches cargo version
  Cargo.lock
  Cargo.toml
  build.rs
  plugin/Version.txt
  plugin/default.project.json
  plugin/src/Config.lua
Labels: type: enhancement, skip changelog

#795 Update rbx_dom dependencies
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  README.md
  plugin/rbx_dom_lua/EncodedValue.lua
  plugin/rbx_dom_lua/EncodedValue.spec.lua
  plugin/rbx_dom_lua/Error.lua
  plugin/rbx_dom_lua/base64.lua
  plugin/rbx_dom_lua/base64.spec.lua
  plugin/rbx_dom_lua/customProperties.lua
  plugin/rbx_dom_lua/database.json
  plugin/rbx_dom_lua/init.lua
  plugin/rbx_dom_lua/init.spec.lua
Labels: scope: cli, skip changelog

#797 Properly handle build metadata in semver parsing in plugin
  CHANGELOG.md
  plugin/src/Config.lua
Labels: scope: plugin

#803 rbx_dom_lua rojo-rbx/rbx-dom@0e10232b (SecurityCapabilities)
  plugin/rbx_dom_lua/EncodedValue.lua
Labels: skip changelog

#804 Fix PatchTree incorrect changeList entries on decode failure
  plugin/src/PatchTree.lua
Labels: skip changelog

#805 Demote unapplied patch warnings to debug logs
  plugin/src/ServeSession.lua
Labels: skip changelog

#807 Bump rbx_binary to 0.7.3
  Cargo.lock
  Cargo.toml
Labels: skip changelog

#810 Remove unnecessary borrows
  build.rs
  src/multimap.rs
  src/web/api.rs
Labels: skip changelog
