Repository rojo-rbx/rojo, pull requests merged in 2023-06, with the labels that each got.

#675 Fix disconnected session activity
  plugin/src/ApiContext.lua
  plugin/src/ServeSession.lua
Labels: status: needs review

#696 Change gitmodules from ssh to https
  .gitmodules
Labels: type: tech debt

#693 Add PRs 674 and 675 to changelog
  CHANGELOG.md
Labels: scope: docs, size: small

#680 Fix change processor clippy lints
  src/change_processor.rs
Labels: scope: cli, type: tech debt

#681 Fix cli clippy lints
  src/cli/fmt_project.rs
  src/cli/init.rs
  src/cli/serve.rs
  src/cli/upload.rs
Labels: scope: cli, type: tech debt

#682 Fix memofs clippy lints
  crates/memofs/src/in_memory_fs.rs
  crates/memofs/src/lib.rs
  crates/memofs/src/noop_backend.rs
  crates/memofs/src/std_backend.rs
Labels: scope: cli, type: tech debt

#683 Fix project clippy lints
  src/project.rs
Labels: scope: cli, type: tech debt

#684 Fix serve session clippy lints
  src/serve_session.rs
Labels: scope: cli, type: tech debt

#685 Fix snapshot clippy lints
  src/snapshot/patch_apply.rs
  src/snapshot/patch_compute.rs
  src/snapshot/tree.rs
Labels: scope: cli, type: tech debt

#686 Fix snapshot middleware clippy lints
  src/snapshot_middleware/dir.rs
  src/snapshot_middleware/util.rs
Labels: scope: cli, type: tech debt

#687 Fix remaining clippy lints
  build.rs
  src/lua_ast.rs
  src/path_serializer.rs
  src/web/interface.rs
Labels: scope: cli, type: tech debt

#688 Skip confirming patches that only contain a datamodel name change
  CHANGELOG.md
  plugin/src/App/init.lua
  plugin/src/PatchSet.lua
Labels: scope: plugin, impact: small, status: needs review

#691 Add protection against syncing non place projects
  CHANGELOG.md
  plugin/src/ServeSession.lua
Labels: type: enhancement, scope: plugin, size: small
