Repository rojo-rbx/rojo, pull requests merged in 2023-08, with the labels that each got.

#755 Fix PatchTree performance issues
  CHANGELOG.md
  plugin/src/PatchTree.lua
Labels: type: bug, scope: plugin, impact: high, size: small, status: needs review

#763 Fix theme
  plugin/src/App/Theme.lua
Labels: type: bug, scope: plugin, status: needs review, skip changelog

#768 Update rbx_dom dependencies
  Cargo.lock
  Cargo.toml
  plugin/rbx_dom_lua/EncodedValue.lua
  plugin/rbx_dom_lua/allValues.json
  plugin/rbx_dom_lua/customProperties.lua
  plugin/rbx_dom_lua/database.json
Labels: meta, skip changelog

#770 Add ambiguous value support for MaterialColors
  CHANGELOG.md
  src/resolution.rs
Labels: type: enhancement

#771 Allow `Terrain` to be included in projects without a classname
  CHANGELOG.md
  src/snapshot_middleware/project.rs
Labels: type: enhancement

#775 Update rbx_dom_lua to rojo-rbx/rbx-dom@7b03132
  plugin/rbx_dom_lua/EncodedValue.lua
  plugin/rbx_dom_lua/EncodedValue.spec.lua
Labels: skip changelog

#774 Confirmation behaviors
  CHANGELOG.md
  plugin/src/App/Components/TextInput.lua
  plugin/src/App/StatusPages/Settings/Setting.lua
  plugin/src/App/StatusPages/Settings/init.lua
  plugin/src/App/Theme.lua
  plugin/src/App/init.lua
  plugin/src/PatchSet.lua
  plugin/src/Settings.lua
Labels: type: enhancement, scope: plugin, size: small, impact: medium, status: needs review
