Repository rojo-rbx/rojo, pull requests merged in 2024-07, with the labels that each got.

#917 Correct issue with default.project.json files with no name being named `default` after change
  rojo-test/serve-test-snapshots/end_to_end__tests__serve__no_name_top_level_project_all-2.snap
  rojo-test/serve-test-snapshots/end_to_end__tests__serve__sync_rule_no_name_project_all.snap
  rojo-test/serve-test-snapshots/end_to_end__tests__serve__sync_rule_no_name_project_info.snap
  rojo-test/serve-tests/sync_rule_no_name_project/default.project.json
  rojo-test/serve-tests/sync_rule_no_name_project/src/not_a_project.rojo
  src/cli/fmt_project.rs
  src/project.rs
  src/serve_session.rs
  src/snapshot_middleware/mod.rs
  src/snapshot_middleware/project.rs
  src/snapshot_middleware/snapshots/librojo__snapshot_middleware__project__test__no_name_project.snap
  tests/rojo_test/serve_util.rs
  tests/tests/serve.rs
Labels: skip changelog

#945 Sleep between file copies and serve for macOS serve tests
  tests/rojo_test/serve_util.rs
Labels: skip changelog

#946 Backport #893 and #903 to Rojo 7.4
  CHANGELOG.md
  crates/memofs/src/lib.rs
  plugin/src/App/StatusPages/Settings/init.lua
  plugin/src/App/init.lua
Labels: scope: cli, version 7.4

#947 Backport #917 to Rojo 7.4.x branch
  rojo-test/serve-test-snapshots/end_to_end__tests__serve__no_name_top_level_project_all-2.snap
  src/cli/fmt_project.rs
  src/project.rs
  src/serve_session.rs
  src/snapshot_middleware/project.rs
  tests/rojo_test/serve_util.rs
  tests/tests/serve.rs
Labels: scope: cli, skip changelog, version 7.4

#948 Update rbx_dom for 7.4.x branch
  Cargo.lock
  Cargo.toml
  plugin/rbx_dom_lua/customProperties.lua
  plugin/rbx_dom_lua/database.json
Labels: skip changelog, version 7.4

#949 Update memofs in 7.4.x branch
  Cargo.lock
  Cargo.toml
  crates/memofs/CHANGELOG.md
  crates/memofs/Cargo.toml
Labels: type: tech debt, version 7.4

#950 Release v7.4.2
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  plugin/Version.txt
Labels: skip changelog, version 7.4
