Repository rojo-rbx/rojo, pull requests merged in 2025-04, with the labels that each got.

#1023 Update rbx-dom
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  plugin/rbx_dom_lua/EncodedValue.lua
  plugin/rbx_dom_lua/Error.lua
  plugin/rbx_dom_lua/allValues.json
  plugin/rbx_dom_lua/customProperties.lua
  plugin/rbx_dom_lua/database.json
  src/cli/sourcemap.rs
  src/project.rs
  src/resolution.rs
  src/snapshot/instance_snapshot.rs
  src/snapshot/patch.rs
  src/snapshot/patch_apply.rs
  src/snapshot/patch_compute.rs
  src/snapshot/tests/apply.rs
  src/snapshot/tests/compute.rs
  src/snapshot/tree.rs
  src/snapshot_middleware/csv.rs
  src/snapshot_middleware/json.rs
  src/snapshot_middleware/json_model.rs
  src/snapshot_middleware/lua.rs
  src/snapshot_middleware/meta_file.rs
  src/snapshot_middleware/project.rs
  src/snapshot_middleware/toml.rs
  src/snapshot_middleware/txt.rs
  src/tree_view.rs
  src/web/api.rs
  src/web/interface.rs
  src/web/ui.rs
Labels: dependencies

#1029 Update rbx-dom-lua database to latest version
  plugin/rbx_dom_lua/database.json
Labels: scope: plugin, skip changelog

#1027 Re-add the hack to write NeedsPivotMigration as `false` for models
  CHANGELOG.md
  rojo-test/build-test-snapshots/end_to_end__tests__build__init_meta_class_name.snap
  rojo-test/build-test-snapshots/end_to_end__tests__build__rbxmx_in_folder.snap
  rojo-test/build-test-snapshots/end_to_end__tests__build__unresolved_values.snap
  rojo-test/serve-test-snapshots/end_to_end__tests__serve__empty_json_model_all-2.snap
  rojo-test/serve-test-snapshots/end_to_end__tests__serve__empty_json_model_subscribe.snap
  rojo-test/serve-test-snapshots/end_to_end__tests__serve__model_pivot_migration_all-2.snap
  rojo-test/serve-test-snapshots/end_to_end__tests__serve__model_pivot_migration_all.snap
  rojo-test/serve-test-snapshots/end_to_end__tests__serve__pivot_migration_all.snap
  rojo-test/serve-test-snapshots/end_to_end__tests__serve__pivot_migration_info.snap
  rojo-test/serve-test-snapshots/end_to_end__tests__serve__ref_properties_all-2.snap
  rojo-test/serve-test-snapshots/end_to_end__tests__serve__ref_properties_all.snap
  rojo-test/serve-test-snapshots/end_to_end__tests__serve__ref_properties_patch_update_all-2.snap
  rojo-test/serve-test-snapshots/end_to_end__tests__serve__ref_properties_patch_update_all.snap
  rojo-test/serve-test-snapshots/end_to_end__tests__serve__ref_properties_patch_update_subscribe.snap
  rojo-test/serve-test-snapshots/end_to_end__tests__serve__ref_properties_subscribe.snap
  rojo-test/serve-tests/pivot_migration/Tool.model.json
  rojo-test/serve-tests/pivot_migration/default.project.json
  src/snapshot/patch_compute.rs
  src/snapshot/tree.rs
  tests/tests/serve.rs
Labels: scope: cli

#1005 Fixes issues with refs in the plugin.
  .gitignore
  plugin/fmt/init.lua
  plugin/http/Response.lua
  plugin/http/init.spec.lua
  plugin/log/init.lua
  plugin/log/init.spec.lua
  plugin/src/Reconciler/applyPatch.lua
  plugin/src/Reconciler/diff.lua
  plugin/src/Reconciler/reify.lua
  plugin/src/Reconciler/reify.spec.lua
Labels: scope: plugin, skip changelog

#1034 Change release build linux version to ubuntu-latest
  .github/workflows/release.yml
Labels: skip changelog
